#  redis:
##    host: 127.0.0.1
##    port: 6379
#    password: 123456
#    database: 0
#    timeout: 100
#    jedis.pool.max-active: 8
#    jedis.pool.max-wait: -1
#    jedis.pool.max-idle: 8
#    jedis.pool.min-idle: 0
#
#    sentinel:
#      master: mymaster
#      nodes:
#        - 127.0.0.1:6800
#        - 127.0.0.1:6801
#        - 127.0.0.1:6802